version: '3'

services:
  web:
    image: cloud-computing-2324:latest
    ports:
      - "8080:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
