name: Build and push Docker imaje 

on:
  push:
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Dcoker image
        env:
          REPOSITORY : cloud-computing-2324
          IMAGE_TAG: latest
        run: |
           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG
          
        