name: Docker hub Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ DOCKER_HUB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ilyasszg/cloud-computing-2324:latest
          ilyasszg/cloud-computing-2324:${{ github.sha }}
